var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "        !!!!!!                            !!                              !!!   ",
   "       !      !  x                                                        xxx   ",
   "          !!      xxxx             !!!!!!!!!!!!!!!!                     x       ",
   "       !yyyyyyy!                  xxxxxxxxxxxxxxxxxx                  x         ",
   "       !!xxxxx!!   xxxxxx                                          x            ",
   "       xxxxxxxx                                                 xx              ",
   "                        xxxxxx                        o   xxxx                  ",
   "                                    o                xx                         ",
   "                          o     xxxxxxxx  xxxxxxxxxxx                        !  ",
   "                 o        x                                              x  xx  ",
   "  xx            xx   xxxx   xxxx                                     xx      x  ",
   "  x!          xxxx     x!!!!!x     x!!x  xxxxx!!!!              xxx          x  ",
   "  x!        xxxxxx     x!!!!!x     x!!x  xxxxx xyx     xx                    x  ",
   "  x!       xxxxxxx     x!!!!!x     x!!x        xxx xyx    !xxx!              x  ",
   "  x!@     xxxxxxxx     x!!!!!x     x!!x            xyx    !!!!!!!xxxxx!!!!!  x  ",
   "  xxx xxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx!!xxxxxxxxxx!!!!!xxxxxxx!!!xxxxxxxxx  ",
   "    x!!!x                     x!!!x      x!!x                                   ",
   "    x!!!x                     x!!!x      xxxx                                   ",
   "    x!!!x                     x!!!x                                             ",
   "    xxxxx                     xxxxx                                             ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                             x!x  ",
   "                                                                        xxxx                                 x!x  ",
   "                                                              xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                               x!x  ",
   "                                       xxx!xxxxxx!!x         x                                               x!x  ",
   "                                       xxxvxxxx xx!x         x                                              xx!x  ",
   "      xxxxxx!xxxxxxxxxxx!xx                      x!x         xxxxxxxxxxxxxxx                  xxxxxxxxxxxxxxx!!x  ",
   "      xxxxxx!xxxxxxxxxxx!xx                      xvx         xxxxxxxxxxxxxxx xxxxxxxxxx          !!!!!!!!!!!!!!xx ",
   "      xxxxxx!xxxxxxxxxxx!xx                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                ",
   "            v           v                                     xx!!!!!!!!!!!xx xxxxxxxxxxxxxxxxxxxxx           v   ",
   "                                                               xvxx!!!!!xvxx   xxxxxxxxxxxxxx                     ",
   "                                                       o                      xxxxxxxxxxxxxxxxxxxxx   xxx         ",
   "  @     o                                                                     xxxxxxxxxxxxxxxxxxxxx   x x         ",
   " xxxxxxxxxx                                   o    xxxxxxxx                   xxxxxxxxxxxxxxxxxxxxx     x         ",
   "    x x                                                              o        xxxxxxxxxxxxxxxxxxxxx     xx        ",
   "    x x                          o          xxxxx    x                        xxxxxxxxxxxxxxxxxxxxx     x         ",
   "    x x          o                             x     x             xxxxxx     xxxxxxxxxxxxxxxxxxxxx     x         ",
   "    x x                   xxxxxxx   xxxxxx     x     x                        xxxxxxxxxxxxxxxxxxxxx     x         ",
   "    x x       xxxxxxxxx         x   x          xxxxxxx     xxxxxx            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "    x x      xx       xx        x   x          xxxxxxx                       xxxxxxxxxxxxxxxxxxxxxx               ",
   "    x x      x         x        x   x          xxxxxxx      =               ox                                    ",
   "    x x      x         x        x   x          xxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       ",
   "    x x      x         x       xx   xx         xxxxxxx     xxxxxxxx  xxxxxxxxxxxx                                 ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!!!!     xxxxxxxxxxxxx                                ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!!xx!     xxxxxxxxxxxxx                                ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx!!!!!!xx !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!xxxxxx!!!!!!xx  !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  [" x           xx!!!!!!!!!!!!!!!!!!!!!x                                                                         ",
   " x           xxxxvxxxxxvxxxxxxxvxxxxx                                                                         ",
   " x                                                                                                            ",
   " x@                                                                                                           ",
   "  x      o       o     o                                                                                      ",
   "  x          =       =          o                                                                             ",
   " x          xxxx  xxxxx      =                                                                                ",
   " xxxxxxx                xxxxxxxxxx                                                                            "],

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
